kubeScheduler:
  enabled: false
kubeControllerManager:
  enabled: false

alertmanager:
    config:
      global:
        resolve_timeout: 5m
        slack_api_url: https://hooks.slack.com/services/*
    alertmanagerSpec:
      alertmanagerConfigNamespaceSelector:
      alertmanagerConfigSelector:
      alertmanagerConfigMatcherStrategy:
        type: None
grafana:
  adminPassword: admin
  enabled: true
  namespaceOverride: "monitoring"
  ingress:
    enabled: true
    ingressClassName: nginx
    hosts:
      - grafana.deyan.itgix.eu
