apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: global-alert-manager-configuration
  namespace: monitoring
  labels:
    release: kube-prometheus
spec:
  groups:
    - name: application-load-alerts
      rules:
        - alert: HighCPUUsage
          expr: 100 - (avg by(instance) (irate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: High CPU usage detected on {{ $labels.instance }}
        - alert: HighMemoryUsage
          expr: (node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes > 0.9
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: High memory usage detected on {{ $labels.instance }}
        - alert: LowDiskSpace
          expr: (node_filesystem_avail_bytes{mountpoint="/"} / node_filesystem_size_bytes{mountpoint="/"}) < 0.5
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Disk space is running low on {{ $labels.device }}
        - alert: HighNetworkDropRate
          expr: rate(node_network_receive_drop_total[5m]) > 100
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: High network packet drop rate detected on {{ $labels.instance }}
        - alert: Watchdog
          expr: vector(1)
          labels:
            severity: none
          annotations:
            summary: This is for test, no problem with the application
